<a href="https://colab.research.google.com/github/anumodit740/Diabetes_risk_prediction/blob/main/Finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip "/content/drive/MyDrive/Financial_dashboard" -d "/content/project_folder"

Archive:  /content/drive/MyDrive/Financial_dashboard
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/cleaned/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/data_dictionary.md
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_1.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_10.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_11.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_12.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_13.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_14.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_15.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_16.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_17.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_18.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_19.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_2.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_20.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_21.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_22.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_23.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_24.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_25.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_3.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_4.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_5.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_6.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_7.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_8.xlsx
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw/combined_part_9.xlsx
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/02_sql/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/02_sql/01_create_tables.sql
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/02_sql/02_data_quality.sql
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/02_sql/03_analysis_queries.sql
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/02_sql/04_interview_queries.sql
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/03_powerbi/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/03_powerbi/dax_measures.md
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/03_powerbi/screenshots/
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/04_docs/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/04_docs/business_insights.md
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/04_docs/interview_prep.md
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/04_docs/screenshots/
   creating: /content/project_folder/Financial-Credit-Risk-Analytics/05_notebooks/
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/05_notebooks/eda.ipynb
  inflating: /content/project_folder/Financial-Credit-Risk-Analytics/README.md

In [ ]:
import os
os.chdir('/content/project_folder')

In [ ]:
!ls

Financial-Credit-Risk-Analytics

In [ ]:
import os
os.chdir('/content/project_folder/Financial-Credit-Risk-Analytics')

In [ ]:
!ls

01_data  02_sql  03_powerbi  04_docs  05_notebooks  README.md

In [ ]:
import pandas as pd
import os

raw_path = "/content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw"

inventory = []

for file in os.listdir(raw_path):

    if file.endswith(".xlsx"):

        file_path = os.path.join(raw_path, file)

        df = pd.read_excel(file_path)

        inventory.append({
            "File": file,
            "Rows": df.shape[0],
            "Columns": df.shape[1]
        })

        print("\n" + "="*80)
        print(file)
        print("Shape:", df.shape)
        print("Columns:")
        print(df.columns.tolist())

================================================================================
combined_part_20.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_14.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_23.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_22.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_4.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_18.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_7.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_3.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_15.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_9.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_25.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_12.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_11.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_17.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_13.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_24.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_8.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_1.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_21.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_6.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_10.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_5.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_19.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_16.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

================================================================================
combined_part_2.xlsx
Shape: (6000, 28)
Columns:
['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 'Credit_Score']

In [ ]:
import pandas as pd
import os

folder_path = "/content/project_folder/Financial-Credit-Risk-Analytics/01_data/raw"

dfs = []

for file in os.listdir(folder_path):
    if file.endswith(".xlsx"):
        df = pd.read_excel(os.path.join(folder_path, file))
        dfs.append(df)

financial_df = pd.concat(dfs, ignore_index=True)

print(financial_df.shape)

(150000, 28)

In [ ]:
clean_path = "/content/project_folder/Financial-Credit-Risk-Analytics/01_data/cleaned"

financial_df.to_csv(
    f"{clean_path}/financial_master_raw.csv",
    index=False
)

In [ ]:
financial_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        150000 non-null  object
 1   Customer_ID               150000 non-null  object
 2   Month                     150000 non-null  object
 3   Name                      135000 non-null  object
 4   Age                       150000 non-null  object
 5   SSN                       150000 non-null  object
 6   Occupation                150000 non-null  object
 7   Annual_Income             150000 non-null  object
 8   Monthly_Inhand_Salary     127500 non-null  float64
 9   Num_Bank_Accounts         150000 non-null  int64
 10  Num_Credit_Card           150000 non-null  int64
 11  Interest_Rate             150000 non-null  int64
 12  Num_of_Loan               150000 non-null  object
 13  Type_of_Loan              132888 non-null  object
 14  Delay_from_due_date       150000 non-null  int64
 15  Num_of_Delayed_Payment    139500 non-null  object
 16  Changed_Credit_Limit      150000 non-null  object
 17  Num_Credit_Inquiries      147000 non-null  float64
 18  Credit_Mix                150000 non-null  object
 19  Outstanding_Debt          150000 non-null  object
 20  Credit_Utilization_Ratio  150000 non-null  float64
 21  Credit_History_Age        136500 non-null  object
 22  Payment_of_Min_Amount     150000 non-null  object
 23  Total_EMI_per_month       150000 non-null  float64
 24  Amount_invested_monthly   143250 non-null  object
 25  Payment_Behaviour         150000 non-null  object
 26  Monthly_Balance           148238 non-null  object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 32.0+ MB

In [ ]:
financial_df.isnull().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                        15000
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       22500
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                17112
Delay_from_due_date             0
Num_of_Delayed_Payment      10500
Changed_Credit_Limit            0
Num_Credit_Inquiries         3000
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age          13500
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      6750
Payment_Behaviour               0
Monthly_Balance              1762
Credit_Score                50000
dtype: int64

In [ ]:
financial_df.duplicated().sum()

np.int64(0)

In [ ]:
financial_df['Credit_Score'].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

In [ ]:
financial_df['Credit_Score'].unique()

array(['Standard', 'Good', 'Poor', nan], dtype=object)

In [ ]:
financial_df.isnull().sum().sort_values(ascending=False)

Credit_Score                50000
Monthly_Inhand_Salary       22500
Type_of_Loan                17112
Name                        15000
Credit_History_Age          13500
Num_of_Delayed_Payment      10500
Amount_invested_monthly      6750
Num_Credit_Inquiries         3000
Monthly_Balance              1762
Month                           0
Customer_ID                     0
ID                              0
Interest_Rate                   0
Num_Credit_Card                 0
Num_Bank_Accounts               0
Annual_Income                   0
SSN                             0
Occupation                      0
Age                             0
Num_of_Loan                     0
Outstanding_Debt                0
Credit_Mix                      0
Changed_Credit_Limit            0
Delay_from_due_date             0
Total_EMI_per_month             0
Payment_of_Min_Amount           0
Credit_Utilization_Ratio        0
Payment_Behaviour               0
dtype: int64

In [ ]:
financial_df.describe(include='all')

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
count,150000,150000,150000,135000,150000,150000,150000,150000,127500.000000,150000.000000,...,150000,150000,150000.000000,136500,150000,150000.000000,143250,150000,148238,100000
unique,150000,12500,12,10139,2524,12501,16,21192,NaN,NaN,...,4,13622,NaN,408,3,NaN,136497,7,148224,3
top,0xa271,CUS_0xb43,January,Stevex,39,#F%$D@*&8,_______,36585.12,NaN,NaN,...,Standard,1360.45,NaN,17 Years and 11 Months,Yes,NaN,__10000__,Low_spent_Small_value_payments,__-333333333333333333333333333__,Standard
freq,1,12,12500,66,4198,8400,10500,24,NaN,NaN,...,54858,36,NaN,628,78484,NaN,6480,38207,15,53174
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4190.115139,17.006940,...,NaN,NaN,32.283309,NaN,NaN,1432.513579,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3180.489657,117.069476,...,NaN,NaN,5.113315,NaN,NaN,8403.759977,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.645417,-1.000000,...,NaN,NaN,20.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1625.265833,3.000000,...,NaN,NaN,28.054731,NaN,NaN,30.947775,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3091.000000,6.000000,...,NaN,NaN,32.297058,NaN,NaN,71.280006,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5948.454596,7.000000,...,NaN,NaN,36.487954,NaN,NaN,166.279555,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15204.633333,1798.000000,...,NaN,NaN,50.000000,NaN,NaN,82398.000000,NaN,NaN,NaN,NaN

In [ ]:
!pip install ydata-profiling
from ydata_profiling import ProfileReport

profile = ProfileReport(
    financial_df,
    title="Financial Credit Risk EDA"
)

profile.to_file("credit_risk_eda.html")

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 8.4 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 16.1 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 59.2 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 27.4 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 4.6 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.2 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

/tmp/ipykernel_7627/4159810988.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/28 [00:00<?, ?it/s]
  4%|▎         | 1/28 [00:04<02:00,  4.47s/it]
  7%|▋         | 2/28 [00:04<00:50,  1.92s/it]
 14%|█▍        | 4/28 [00:07<00:35,  1.47s/it]
 21%|██▏       | 6/28 [00:07<00:20,  1.06it/s]
 29%|██▊       | 8/28 [00:08<00:13,  1.47it/s]
 43%|████▎     | 12/28 [00:08<00:05,  2.93it/s]
 46%|████▋     | 13/28 [00:08<00:05,  2.81it/s]
 50%|█████     | 14/28 [00:10<00:06,  2.04it/s]
 54%|█████▎    | 15/28 [00:10<00:05,  2.39it/s]
 61%|██████    | 17/28 [00:11<00:04,  2.37it/s]
 64%|██████▍   | 18/28 [00:11<00:03,  2.59it/s]
 68%|██████▊   | 19/28 [00:11<00:02,  3.09it/s]
 71%|███████▏  | 20/28 [00:12<00:03,  2.49it/s]
 75%|███████▌  | 21/28 [00:12<00:02,  2.62it/s]
 79%|███████▊  | 22/28 [00:13<00:02,  2.04it/s]
 86%|████████▌ | 24/28 [00:13<00:01,  2.75it/s]
 89%|████████▉ | 25/28 [00:17<00:03,  1.31s/it]
100%|██████████| 28/28 [00:18<00:00,  1.55it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
profile.get_description().alerts

[[Delay_from_due_date] is highly overall correlated with [Interest_Rate] and 1 other fields,
 [Interest_Rate] is highly overall correlated with [Delay_from_due_date] and 2 other fields,
 [Num_Bank_Accounts] is highly overall correlated with [Delay_from_due_date] and 1 other fields,
 [Num_Credit_Inquiries] is highly overall correlated with [Interest_Rate],
 [Name] 15000 (10.0%) missing values,
 [Monthly_Inhand_Salary] 22500 (15.0%) missing values,
 [Type_of_Loan] 17112 (11.4%) missing values,
 [Num_of_Delayed_Payment] 10500 (7.0%) missing values,
 [Num_Credit_Inquiries] 3000 (2.0%) missing values,
 [Credit_History_Age] 13500 (9.0%) missing values,
 [Amount_invested_monthly] 6750 (4.5%) missing values,
 [Monthly_Balance] 1762 (1.2%) missing values,
 [Credit_Score] 50000 (33.3%) missing values,
 [Monthly_Balance] was rejected,
 [Month] is uniformly distributed,
 [ID] has unique values,
 [Credit_Utilization_Ratio] has unique values,
 [Monthly_Balance] is an unsupported type, check if it needs cleaning or further analysis,
 [Num_Bank_Accounts] has 6494 (4.3%) zeros,
 [Delay_from_due_date] has 1821 (1.2%) zeros,
 [Num_Credit_Inquiries] has 8074 (5.4%) zeros,
 [Total_EMI_per_month] has 15615 (10.4%) zeros]